[package]
name = "tp-behavioural-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/file_server.rs"

[[bin]]
name = "client"
path = "src/file_client.rs"
